const PREFIX = 'svg-icon-creator';

export const LOCAL_STORE_KEYS = {
  SCALE_ALT: `${PREFIX}-SCALE_ALT`,
  SCALE_NORMAL: `${PREFIX}-SCALE_NORMAL`,
  SCALE_SHIFT: `${PREFIX}-SCALE_SHIFT`,
  MOVE_ALT: `${PREFIX}-MOVE_ALT`,
  MOVE_NORMAL: `${PREFIX}-MOVE_NORMAL`,
  MOVE_SHIFT: `${PREFIX}-MOVE_SHIFT`,
  DECIMAL_PRECISION: `${PREFIX}-DECIMAL_PRECISION`,
};
