export const LOCAL_STORE_KEYS = {
  SCALE_ALT: 'SCALE_ALT',
  SCALE_NORMAL: 'SCALE_NORMAL',
  SCALE_SHIFT: 'SCALE_SHIFT',
  MOVE_ALT: 'MOVE_ALT',
  MOVE_NORMAL: 'MOVE_NORMAL',
  MOVE_SHIFT: 'MOVE_SHIFT',
};
